version: '3.8'

services:
  syntax-realty:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: syntax-realty-adk
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - GOOGLE_CLOUD_PROJECT=promptoptmizer
      # By leaving these without values, Docker Compose will grab them
      # from your active terminal session automatically.
      - GOOGLE_API_KEY
      - GOOGLE_GENAI_USE_VERTEXAI
    volumes:
      - ./:/app
    ipc: host